version: "3.7"
services:
  node:
    container_name: shakespeare
    build: ./docker/
    image: nodeapp:shakespeare
    command: sh
    volumes:
      - .:/app
    working_dir: '/app'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    ports:
      - 5000:5000
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - JWT_PVT=${JWT_PVT}
      - JWT_SALT=${JWT_SALT}
      - JWT_EXPIRE=${JWT_EXPIRE}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
