version: "3"
services:
  nodedev:
    container_name: shakespeare
    build: ./docker/
    command: sh
    volumes:
      - .:/app
    working_dir: '/app'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    ports:
      - 5000:5000
      - 3000:3000
    restart: always
