steps:
  - label: Start Pipeline
    command: echo "Hello!"

  - wait

steps:
  - label: ':npm: NPM Install'
    command: 'npm install'

  - wait

# steps:
#   - label: ':hammer: Tests'
#     command: 'npm test'