steps:
  - label: ':hammer: Tests'
    command: 'npm install && cd client && npm install && npm run build && cd .. && npm test'

  - wait

  - label: ':heroku: Deploy to Heroku'
    command:
      - 'git remote add heroku https://git.heroku.com/shakespeare-sunday.git'
      - 'git push heroku master'
    branches: 'master'
